/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppDrawer: typeof import('./components/layout/AppDrawer.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    ButtonSettings: typeof import('./components/layout/ButtonSettings.vue')['default']
  }
}
